apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-app
spec:
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
      name: https
  #  - port: 30001
  #    nodePort: 30001
  #    protocol: TCP
  #    name: ssh
  selector:
    app: nginx-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Never
          #env:
          #  - name: SSH_USER
          #    value: admin
          #  - name: SSH_PASSWORD
          #    value: secret
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: 80
          #  initialDelaySeconds: 5
          #  periodSeconds: 5
          #  successThreshold: 1
          #livenessProbe:
          #  tcpSocket:
          #    port: 30001
          #  initialDelaySeconds: 5
          #  periodSeconds: 5
          #  successThreshold: 1